service: reto-tecnico

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
  apiGateway:
    shouldStartNameWithService: true

functions:
  listPlanets:
    handler: api/swapi.planets
    description: List all planets from SWAPI API
    events:
      - http: 
          method: GET
          path: /planets
          cors: true
  usersSubmission:
    handler: api/reto.submit
    memorySize: 128
    description: Submit user information.
    events:
      - http: 
          method: POST
          path: /user
          cors: true
  listUsers:
    handler: api/reto.list
    memorySize: 128
    description: List all users
    events:
      - http: 
          method: GET
          path: /users
          cors: true  

